version: '3.8'

services:

  vue-js-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: vue-js-app-container

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "5000:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock