version: '3.8'
services:

  vue-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - '/app/node_modules'
    ports:
      - "8080:8080"

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "5000:8080"
    restart: always